### ISSUE TITLE
Add GNU/Linux support

### ISSUE THREAD

**Issue by sedlak477** [Rhatalin/One-Punch-Man-Challange-Counter#1]
Currently as it is, the project does not work on GNU/Linux. That's not great and does not contribute positively to the projects popularity. I think people would greatly benefit from cross-platform support, or even just GNU/Linux support.

**Comment by Rathalin** [comment]
https://medium.com/@hudsonmendes/build-net-4-5-on-linux-in-5-minutes-and-see-what-it-is-like-848ea45fc667
